name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      # Check out the repo and set up python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install -r requirements-dev.txt

      # Install OpenGL so PySide6 works properly
      - name: Install OpenGL
        run: |
          sudo apt-get update
          sudo apt-get install -y -o Acquire::Retries=3 freeglut3 freeglut3-dev

      # Building documentation
      - name: Build Documentation
        run: |
          sphinx-apidoc -o docs/source foundry/
          sphinx-build docs/source public -b dirhtml

      # Build and handle Github Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          public_dir: ./public

      # Upload the artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: public
