name: Tests

on:
  - push
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/actions@v2.0.0

  test:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the repo and set up python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # cache dependencies
      - run: pip install -r requirements-dev.txt

      # Run test suite
      - name: Run tests
        run: python -m pytest tests/ --verbose --failed-first
